### ISSUE TITLE
Preview image does not stay in fullscreen

### ISSUE THREAD

**Issue by AnielaGratz** [wurmf/OpenBooth#35]
Preview image in shotframe does not stay in fullscreen.

**Comment by schrer** [comment]
Scaling on computers with different screen sizes now works correctly, but the problem that one of the screens always goes out of fullscreen when the other comes in still persists. At this point, fixing it looks unrealistic because we probably won't have two screens at the same time in the near future.

**Comment by schrer** [comment]
Apparently having two stages in fullscreen in the same application at the same time is not allowed by the Java-Runtime. This behaviour was once possible and even marked as a bug in OpenJDK [JDK-8114339](https://bugs.openjdk.java.net/browse/JDK-8114339)
An alternative solution was tested (setting the stage style to UNDECORATED) but did not have the desired effect either (sidebars provided by the OS would be still visible in this setting).

Since the UI will be remodeled to only show one window this whole problem will not have an effect in the next version and the issue will be marked as WON'T FIX
